# PostgreSQL connection configuration
default: &default
  adapter: postgresql
  encoding: utf8
  database: pvaldesoiro_development
  username: pablo
  host: localhost
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: library_test
  username: pablo
  host: localhost
  pool: 5
  port: 5432

development:
  adapter: postgresql
  encoding: utf8
  database: library_development
  username: pablo
  host: localhost
  pool: 5
  port: 5432

